// Code generated by entc, DO NOT EDIT.

package ent

import (
	"homework-backend/ent/answer"
	"homework-backend/ent/opt"
	"homework-backend/ent/question"
	"homework-backend/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerFields := schema.Answer{}.Fields()
	_ = answerFields
	// answerDescID is the schema descriptor for id field.
	answerDescID := answerFields[0].Descriptor()
	// answer.DefaultID holds the default value on creation for the id field.
	answer.DefaultID = answerDescID.Default.(func() uuid.UUID)
	optFields := schema.Opt{}.Fields()
	_ = optFields
	// optDescID is the schema descriptor for id field.
	optDescID := optFields[0].Descriptor()
	// opt.DefaultID holds the default value on creation for the id field.
	opt.DefaultID = optDescID.Default.(func() uuid.UUID)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescID is the schema descriptor for id field.
	questionDescID := questionFields[0].Descriptor()
	// question.DefaultID holds the default value on creation for the id field.
	question.DefaultID = questionDescID.Default.(func() uuid.UUID)
}
