// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// Opt is the predicate function for opt builders.
type Opt func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)
