// Code generated by entc, DO NOT EDIT.

package answer

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the answer type in the database.
	Label = "answer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuestionID holds the string denoting the question_id field in the database.
	FieldQuestionID = "question_id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldOptionID holds the string denoting the option_id field in the database.
	FieldOptionID = "option_id"
	// Table holds the table name of the answer in the database.
	Table = "answers"
)

// Columns holds all SQL columns for answer fields.
var Columns = []string{
	FieldID,
	FieldQuestionID,
	FieldBody,
	FieldOptionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
