// Code generated by entc, DO NOT EDIT.

package question

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the question type in the database.
	Label = "question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// EdgeOptions holds the string denoting the options edge name in mutations.
	EdgeOptions = "options"
	// Table holds the table name of the question in the database.
	Table = "questions"
	// OptionsTable is the table that holds the options relation/edge. The primary key declared below.
	OptionsTable = "question_options"
	// OptionsInverseTable is the table name for the Opt entity.
	// It exists in this package in order to avoid circular dependency with the "opt" package.
	OptionsInverseTable = "opts"
)

// Columns holds all SQL columns for question fields.
var Columns = []string{
	FieldID,
	FieldWeight,
	FieldType,
	FieldBody,
}

var (
	// OptionsPrimaryKey and OptionsColumn2 are the table columns denoting the
	// primary key for the options relation (M2M).
	OptionsPrimaryKey = []string{"question_id", "opt_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
